### PR TITLE
chore(deps): upgrade to latest

### PR DESCRIPTION
**Pull request by noammu**
THE UPGRADE OF ESLINT TO V.9 IS REVERTED UNTIL THEY SOLVE ALL OF THEIR PROBLEMS.

### CODE REVIEW

**Review by pilarbuchen — DISMISSED** [review]

**Comment by pilarbuchen** [comment]
@wixc3/react-board": "^2.5.0" is not compatible w/ "eslint": "^9.0.0"

**Comment by pilarbuchen** [comment]
wait .... it loads now .. maybe someone else can check?

**Comment by pilarbuchen** [comment]
this guy def doesnt work w v9

**Comment by noammu** [comment]
It does render the thumbnail,
But great catch with the script. I will check it out.

**Review by pilarbuchen — APPROVED** [review]

**Pull request merged**
